import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import ReduxProvider from "@/components/providers/ReduxProvider";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/components/providers/QueryProvider";
import { CartProvider } from "@/components/providers/CartProvider";
import { OrderNotificationProvider } from "@/components/providers/OrderNotificationProvider";
import NotificationProvider from "@/components/providers/NotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bhojan Nepal",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <QueryProvider>
          <ReduxProvider>
            <CartProvider>
              <OrderNotificationProvider />
              <NotificationProvider>
                <Navbar />
                {/* Main content takes up all available space */}
                <main className="flex-1">{children}</main>
                <Toaster position="top-right" reverseOrder={false} />
                <Footer />
              </NotificationProvider>
            </CartProvider>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
